apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  annotations:
    backstage.io/techdocs-ref: url:https://code.gitlab.prod.us-west-2.tlz.svbank.com/nmalviya/backstage/-/blob/master/index.md
  name: credit-card-service
  description: something
  links: 
    - url: https://bitbucket.corp.svbank.com/projects/EIS/repos/ofx-gatewayservice/browse
      title: bitbucket Repo
      icon: bitbucket
  tags:
    - rest
    - credit-card-service
spec:
  tags:
    - rest
    - credit-card-service
  system: eis-ms
  type: service
  lifecycle: uat
  owner: team-ms
  providesApis:
    - credit-card-service